services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://backend:8000
    networks:
      - scribe
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8000
      - BASE_URL=http://backend:8000
      - CLIENT_DOCKER_URL=http://frontend:3000
      - CLIENT_URL=http://localhost:3000
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=db_scribe
      - AI_API_URL=http://ollama:11434
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo
      - ollama
    networks:
      - scribe
  mongo:
    image: mongo:8.2.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - scribe
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - scribe

volumes:
  mongo_data:
  ollama_data:

networks:
  scribe:
    driver: bridge